// ─── Composition ────────────────────────────────────────────────────────────
export const WIDTH = 1080;
export const HEIGHT = 1920;
export const FPS = 30;

// Full ~41-second timeline:
//   0   – 120 : InvatiqSoft intro splash      (4s)
//   120 – 420 : Pain points slide             (10s extended)
//   420 – 960 : WhatsApp chat                 (18s)
//   960 –1060 : CTA overlay                   (3.3s)
//  1060 –1240 : Outro / DM slide              (6s)
export const DURATION_FRAMES = 1240;

// ─── Section boundaries (absolute frames) ────────────────────────────────────
export const SECTIONS = {
  introStart: 0,
  introEnd: 120,       // 4s  (was 80)

  painStart: 120,
  painEnd: 420,        // 10s (was 160 frames)

  chatStart: 420,

  ctaStart: 960,
  ctaEnd: 1060,

  outroStart: 1060,
  outroEnd: 1240,
};

// ─── Colors ─────────────────────────────────────────────────────────────────
export const COLORS = {
  background: '#E5DDD5',
  headerBg: '#075E54',
  headerText: '#FFFFFF',
  customerBubble: '#DCF8C6',
  botBubble: '#FFFFFF',
  bubbleText: '#111B21',
  timestampText: '#8696A0',
  typingDot: '#8696A0',
  ctaDim: 'rgba(0,0,0,0.72)',
  ctaButtonGlow: '#25D366',
  avatarBg: '#128C7E',
  onlineGreen: '#25D366',
  shadowColor: 'rgba(0,0,0,0.13)',
  brandDark: '#0D1B2A',
  brandBlue: '#1A3C6E',
  brandAccent: '#2B7FE0',
  whatsappGreen: '#25D366',
  narrationBg: 'rgba(0,0,0,0.72)',
};

// ─── Typography ──────────────────────────────────────────────────────────────
export const FONT = {
  family: 'Noto Sans Bengali',
  sizeMessage: 42,
  sizeTimestamp: 26,
  sizeCtaMain: 72,
  sizeCtaSub: 50,
  sizeNarration: 38,
  lineHeight: 1.6,
};

// ─── Bubble geometry ────────────────────────────────────────────────────────
export const BUBBLE = {
  maxWidth: WIDTH * 0.78,
  paddingH: 26,
  paddingV: 18,
  radiusBase: 20,
  radiusTail: 5,
  marginH: 20,
  marginBetween: 14,
};

// ─── Header ──────────────────────────────────────────────────────────────────
export const HEADER = {
  height: 148,
  avatarSize: 84,
  paddingH: 28,
};

// ─── Timing helpers ───────────────────────────────────────────────────────────
export const TIMING = {
  headerFadeIn: 18,
  typingDuration: 18,
  scrollStart: SECTIONS.chatStart + 270,  // frame 690
  ctaStart: SECTIONS.ctaStart,
};

// ─── Subtitle narrations (shown on screen, independent of audio) ──────────────
export interface Narration {
  from: number;
  to: number;
  text: string;
}

// NARRATIONS are synced to the actual voice audio sentence boundaries
// (generated by scripts/generate_audio.py using edge-tts SentenceBoundary events)
// Voice starts at frame 0; sentence offsets are the raw audio timings.
// Subtitle timings synced 1:1 with actual voice sentence boundaries
// (from scripts/generate_audio.py SentenceBoundary events)
// Timings synced to bn-BD-PradeepNeural male voice (+22% rate)
export const NARRATIONS: Narration[] = [
  { from: 3,    to: 103,  text: 'ইনভাটিক সফট নিয়ে আসছে আপনার ব্যবসার জন্য এ আই বট!' },
  { from: 101,  to: 161,  text: 'আপনিও কি এই সমস্যায় আছেন?' },
  { from: 161,  to: 234,  text: 'রাতে রিপ্লাই নেই, কাস্টমার চলে যায়' },
  { from: 234,  to: 296,  text: 'ম্যানুয়াল অর্ডারে সময় নষ্ট' },
  { from: 296,  to: 350,  text: 'দেরিতে বিক্রি কমে যায়' },
  { from: 350,  to: 422,  text: 'একই প্রশ্নে বারবার উত্তর দিতে হয়' },
  { from: 422,  to: 515,  text: 'আমাদের এ আই বট চব্বিশ ঘণ্টা এই সব সমাধান করে' },
  { from: 515,  to: 637,  text: 'দেখুন কীভাবে বট রিপ্লাই দেয়, পণ্য দেখায়, অর্ডার নেয়, কনফার্ম করে' },
  { from: 637,  to: 713,  text: 'কোনো মানুষ লাগেনি, সম্পূর্ণ অটোমেটিক!' },
  { from: 713,  to: 798,  text: 'আমাদের বট আপনার দোকানের হয়ে দিনরাত কাজ করে' },
  { from: 798,  to: 879,  text: 'বিক্রি বাড়ান, সময় বাঁচান, ঝামেলা কমান' },
  { from: 879,  to: 945,  text: 'এটা সম্পূর্ণ অটোমেটিক সিস্টেম' },
  { from: 945,  to: 1075, text: 'আমরা সমাধান করি চব্বিশ ঘণ্টা রিপ্লাই, ম্যানুয়াল অর্ডার এবং কাস্টমার ধরে রাখা' },
  { from: 1075, to: 1184, text: 'আজই আমাদের ডিএম করুন, ইনভাটিক সফট এ আই বট শুরু করুন' },
];

// ─── Conversation data ───────────────────────────────────────────────────────
export type Sender = 'customer' | 'bot';

export interface Message {
  sender: Sender;
  text: string;
  timestamp: string;
  /** Absolute frame chat starts at frame 420 (was 240, +180 shift) */
  startFrame: number;
}

export const MESSAGES: Message[] = [
  {
    sender: 'customer',
    text: 'আসসালামু আলাইকুম, আপনাদের পোশাক এর দাম কত?',
    timestamp: '10:41',
    startFrame: 450,   // was 270, +180
  },
  {
    sender: 'bot',
    text: `ওয়ালাইকুম আসসালাম! Sharmin Shop এ আপনাকে স্বাগতম 🙏\n\nআমাদের পণ্যগুলো দেখুন:\n১️⃣ থ্রি-পিস ১২৫০ টাকা\n২️⃣ শাড়ি ১৮০০ টাকা\n৩️⃣ কুর্তি ৯০০ টাকা\n\nকোনটা পছন্দ হয়েছে?`,
    timestamp: '10:41',
    startFrame: 510,   // was 330, +180
  },
  {
    sender: 'customer',
    text: 'কুর্তি টা নিব। সাইজ M আছে?',
    timestamp: '10:42',
    startFrame: 575,   // was 395, +180
  },
  {
    sender: 'bot',
    text: `হ্যাঁ, M সাইজ স্টকে আছে ✅\n\nকুর্তি সাইজ M দাম ৯০০ টাকা\n\nঅর্ডার কনফার্ম করতে আপনার নাম, ঠিকানা এবং মোবাইল নাম্বার দিন।`,
    timestamp: '10:42',
    startFrame: 635,   // was 455, +180
  },
  {
    sender: 'customer',
    text: 'নাম: সুমি আক্তার\nঠিকানা: মিরপুর-১০, ঢাকা\nমোবাইল: ০১৭xxxxxxxx',
    timestamp: '10:43',
    startFrame: 710,   // was 530, +180
  },
  {
    sender: 'bot',
    text: `ধন্যবাদ সুমি আক্তার! 🎉\n\n✅ অর্ডার কনফার্ম হয়েছে\n📦 অর্ডার নং: #1042\n🛍️ পণ্য: কুর্তি (M)\n💰 মূল্য: ৯০০ টাকা (COD)\n🚚 ডেলিভারি: ২-৩ কর্মদিবসের মধ্যে\n\nধন্যবাদ! 💚`,
    timestamp: '10:43',
    startFrame: 780,   // was 600, +180
  },
  {
    sender: 'customer',
    text: 'ওয়াও এত তারাতারি! ধন্যবাদ আপু 😍',
    timestamp: '10:44',
    startFrame: 880,   // was 700, +180
  },
];
