export type Role = "user" | "moderator" | "admin";

export type OrderStatus =
  | "draft"
  | "submitted"
  | "under_review"
  | "delivered"
  | "invoiced";

export interface CatalogItem {
  id: string;
  categoryId: string;
  nameBn: string;
  nameEn: string;
}

export interface CategoryDef {
  id: string;
  nameBn: string;
  nameEn: string;
  items: CatalogItem[];
}

export interface OrderLine {
  id: string;
  serial: number;
  categoryId: string;
  itemId: string;
  itemNameBn: string;
  itemNameEn: string;
  kg: string;
  gram: string;
  piece: string;
  instructions?: string;
  unitPrice?: number;
  lineTotal?: number;
  /** Set when admin generates billing invoice (DB + API). */
  markupPercent?: number;
  markupAmount?: number;
  unitPriceAfterMarkup?: number | null;
  lineTotalAfterMarkup?: number | null;
  profitLossAmount?: number;
}

export interface Order {
  id: string;
  /** Procurement requester (prototype) */
  ownerId?: string;
  orderNo: string;
  orderDate: string;
  /** ISO timestamp when the user confirmed submit (optional on legacy / seed data). */
  submittedAt?: string;
  deliveryDate: string;
  deliveryTime?: string;
  status: OrderStatus;
  billingAddress: string;
  deliveryAddress: string;
  contactPerson: string;
  phone: string;
  lines: OrderLine[];
  signatureDataUrl?: string | null;
  challanGenerated?: boolean;
  /** Generated by moderator for admin procurement review. */
  purchaseInvoiceGenerated?: boolean;
  /** Who generated the purchase invoice (affects purchase billing cycle/payment attribution). */
  purchaseInvoiceGeneratedBy?: "moderator" | "admin";
  /** Generated by admin for final customer billing. */
  billingInvoiceGenerated?: boolean;
  /** @deprecated use billingInvoiceGenerated */
  invoiceGenerated?: boolean;
  subtotal?: number;
  purchaseSubtotal?: number;
  billingSubtotal?: number;
  markupPercent?: number;
  /** Category-wise billing markup (%) used when admin generated billing invoice. */
  billingCategoryMarkups?: Record<string, number>;
  grandTotal?: number;
}

export interface SessionUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: Role;
  billingAddress: string;
  deliveryAddress: string;
}
